CREATE TABLE comments (
    AUTHOR VARCHAR(20),
    BODY TEXT,
    BODY_HTML TEXT,
    TIME_CREATED BIGINT,
    EDITED BOOLEAN,
    COMMENT_ID TEXT NOT NULL,
    POST_ID TEXT NOT NULL,
    IS_SUBMITTER BOOLEAN,
    PARENT_ID TEXT,
    SCORE INT,
    YEAR INT,
    PRIMARY KEY(COMMENT_ID),
    
    CONSTRAINT post_parent
        FOREIGN KEY(POST_ID)
            REFERENCES posts(POST_ID)
            ON DELETE CASCADE
)