CREATE TABLE posts (
    POST_ID VARCHAR(45) NOT NULL,
    POST_TITLE TEXT,
    POST_NAME TEXT,
    AUTHOR VARCHAR(20),
    TIME_CREATED BIGINT,
    EDITED BOOLEAN,
    IS_ORIGINAL BOOLEAN,
    IS_SELF BOOLEAN,
    LOCKED BOOLEAN,
    OVER_18 BOOLEAN,
    NUM_COMMENTS INT,
    SCORE INT,
    UPVOTE_RATIO FLOAT,
    SELFTEXT TEXT,
    YEAR INT,
    PRIMARY KEY(POST_ID)
)